from pathlib import Path

BATCH_WINDOW_US = 1000
BASE_DIR = Path(__file__).parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

BASE_WIDTH = 1280
BASE_HEIGHT = 720

MODEL_LOGGING_VERBOSE = False

YOLO_CONFIDENCE_THRESHOLD = 0.01
HEATMAP_PIXEL_SIZE = 4

CENTROID_EPSILON = 0.8

K_CANDIDATES = [1, 2, 3, 4]

OUTLIER_DISTANCE_MULTIPLIER = 3.0
